# Generated by Django 4.1.3 on 2022-11-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacilpad', '0002_alter_book_cover_alter_book_isbn_alter_book_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='date',
            new_name='release_date',
        ),
    ]
